import type { Metadata } from "next";
import { Geist, Geist_Mono, Calligraffitti, Playfair_Display, Great_Vibes, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const calligraffitti = Calligraffitti({
  weight: "400", 
  variable: "--font-calligraffitti",
  subsets: ["latin"],
});

const playfair_display = Playfair_Display({
  variable: "--font-playfair_display-sans",
  subsets: ["latin"],
});

const great_vibes = Great_Vibes({
  weight: "400", 
  variable: "--font-great_vibes-sans",
  subsets: ["cyrillic"],
});
const montserrat = Montserrat({
  weight: "400", 
  variable: "--font-montserrat-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Шаблон пригласительного на свадьбу",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
